# Generated by Django 5.2.8 on 2025-11-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotee',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Google Drive or image URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='devotee',
            name='sabha_type',
            field=models.CharField(choices=[('bal', 'Bal Sabha'), ('yuvak', 'Yuvak Sabha'), ('mahila', 'Mahila Sabha'), ('general', 'Sanyukt Sabha')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sabha',
            name='sabha_type',
            field=models.CharField(choices=[('bal', 'Bal Sabha'), ('yuvak', 'Yuvak Sabha'), ('mahila', 'Mahila Sabha'), ('general', 'Sanyukt Sabha')], max_length=20),
        ),
    ]
